export default function MonitoringPage() {
  // In a real system, we would embed a Grafana dashboard iframe here,
  // pointing to the Prometheus metrics generated by our MonitoringAgent.
  return (
    <div className="p-8 h-full flex flex-col">
      <h1 className="text-2xl font-bold mb-6">Monitoring & Data Drift</h1>
      <div className="flex-1 bg-white rounded-xl border border-gray-200 shadow-sm flex flex-col items-center justify-center p-8 text-center">
        <div className="bg-gray-100 p-4 rounded-full mb-4">
          <svg className="w-12 h-12 text-gray-400" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z"></path>
          </svg>
        </div>
        <h2 className="text-xl font-semibold text-gray-900 mb-2">Grafana Dashboard Integration</h2>
        <p className="text-gray-500 max-w-md">
          This dashboard connects to Prometheus to visualize the `pr_feature_complexity`, `pr_feature_size`, and `pr_feature_function_count` metrics exposed by the MonitoringAgent.
        </p>
        <div className="mt-8 grid grid-cols-3 gap-6 w-full max-w-3xl">
           <div className="border border-gray-200 rounded-lg p-4 bg-gray-50">
             <div className="text-sm font-medium text-gray-500">Avg Complexity</div>
             <div className="text-2xl font-bold text-gray-900 mt-1">12.4</div>
             <div className="text-xs text-green-600 mt-1">Stable</div>
           </div>
           <div className="border border-gray-200 rounded-lg p-4 bg-gray-50">
             <div className="text-sm font-medium text-gray-500">Data Drift Status</div>
             <div className="text-2xl font-bold text-gray-900 mt-1">None</div>
             <div className="text-xs text-green-600 mt-1">Via Evidently</div>
           </div>
           <div className="border border-gray-200 rounded-lg p-4 bg-gray-50">
             <div className="text-sm font-medium text-gray-500">Models Promoted</div>
             <div className="text-2xl font-bold text-gray-900 mt-1">2</div>
             <div className="text-xs text-blue-600 mt-1">Via MLflow</div>
           </div>
        </div>
      </div>
    </div>
  );
}
