"""Add phase 3 and 4 review columns

Revision ID: 92d1ed0b04a7
Revises: 7aeebc398286
Create Date: 2026-07-20 10:29:05.872587
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '92d1ed0b04a7'
down_revision: str | None = '7aeebc398286'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tags')
    op.drop_table('metrics')
    op.drop_table('params')
    op.drop_table('runs')
    op.drop_table('experiments')
    op.add_column('reviews', sa.Column('security_results', sa.JSON(), nullable=True))
    op.add_column('reviews', sa.Column('explainability_results', sa.JSON(), nullable=True))
    op.add_column('reviews', sa.Column('documentation_results', sa.JSON(), nullable=True))
    op.add_column('reviews', sa.Column('test_generation_results', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('reviewer_recommendation_results', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('deployment_status_results', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reviews', 'deployment_status_results')
    op.drop_column('reviews', 'reviewer_recommendation_results')
    op.drop_column('reviews', 'test_generation_results')
    op.drop_column('reviews', 'documentation_results')
    op.drop_column('reviews', 'explainability_results')
    op.drop_column('reviews', 'security_results')
    op.create_table('tags',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name=op.f('tags_run_uuid_fkey')),
    sa.PrimaryKeyConstraint('key', 'run_uuid', name=op.f('tag_pk'))
    )
    op.create_table('runs',
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('source_name', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('entry_point_name', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('start_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('end_time', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('source_version', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('lifecycle_stage', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('artifact_uri', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.CheckConstraint("lifecycle_stage::text = ANY (ARRAY['active'::character varying, 'deleted'::character varying]::text[])", name=op.f('runs_lifecycle_stage')),
    sa.CheckConstraint("source_type::text = ANY (ARRAY['NOTEBOOK'::character varying, 'JOB'::character varying, 'LOCAL'::character varying, 'UNKNOWN'::character varying, 'PROJECT'::character varying]::text[])", name=op.f('source_type')),
    sa.CheckConstraint("status::text = ANY (ARRAY['SCHEDULED'::character varying, 'FAILED'::character varying, 'FINISHED'::character varying, 'RUNNING'::character varying]::text[])", name=op.f('status')),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.experiment_id'], name=op.f('runs_experiment_id_fkey')),
    sa.PrimaryKeyConstraint('run_uuid', name=op.f('run_pk'))
    )
    op.create_table('metrics',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name=op.f('metrics_run_uuid_fkey')),
    sa.PrimaryKeyConstraint('key', 'timestamp', 'run_uuid', name=op.f('metric_pk'))
    )
    op.create_table('params',
    sa.Column('key', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('value', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('run_uuid', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_uuid'], ['runs.run_uuid'], name=op.f('params_run_uuid_fkey')),
    sa.PrimaryKeyConstraint('key', 'run_uuid', name=op.f('param_pk'))
    )
    op.create_table('experiments',
    sa.Column('experiment_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('artifact_location', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('lifecycle_stage', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.CheckConstraint("lifecycle_stage::text = ANY (ARRAY['active'::character varying, 'deleted'::character varying]::text[])", name=op.f('experiments_lifecycle_stage')),
    sa.PrimaryKeyConstraint('experiment_id', name=op.f('experiment_pk')),
    sa.UniqueConstraint('name', name=op.f('experiments_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
