apiVersion: v1
kind: Service
metadata:
  name: reviewops-backend
  labels:
    app: reviewops-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: reviewops-backend
